### ISSUE TITLE
DaprException rpc error - all SubConns are in TransientFailure

### ISSUE THREAD

**Issue by RicardoNiepel** [dapr/docs#185] opened 2019-10-23 16:17 UTC
## Expected Behavior

Local development possibility with multiple parallel dapr processes.

I have multiple apps (.NET) and start them with individual dapr cli calls in parellel, like

`dapr run --app-id ingress --app-port 5000 dotnet run`
and
`dapr run --app-id actor --app-port 3000 dotnet run`

## Actual Behavior

Unpredictable for me, sometimes after I've started both, I'm getting an exception.
I've tried to change the order of stating both - still sometimes this comes up:

```
== APP == Dapr.Actors.DaprException: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 169.254.XXX.XXX:50477: connectex: No connection could be made because the target machine actively refused it."
== APP ==    at Dapr.Actors.DaprHttpInteractor.SendAsyncHandleUnsuccessfulResponse(Func`1 requestFunc, String relativeUri, String requestId, CancellationToken cancellationToken)
== APP ==    at Dapr.Actors.DaprHttpInteractor.SendAsync(Func`1 requestFunc, String relativeUri, String requestId, CancellationToken cancellationToken)
== APP ==    at Dapr.Actors.DaprHttpInteractor.InvokeActorMethodWithoutRemotingAsync(String actorType, String actorId, String methodName, String jsonPayload, CancellationToken cancellationToken)
== APP ==    at SampleubSub.Ingress.Startup.<>c__DisplayClass3_0.<<Configure>g__RouteToActor|3>d.MoveNext() in Startup.cs:line 107
== APP == --- End of stack trace from previous location where exception was thrown ---
== APP ==    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
== APP ==    at Dapr.CloudEventsMiddleware.ProcessBodyAsync(HttpContext httpContext, String charSet)
== APP ==    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

## Steps to Reproduce the Problem

I don't know if this error relates to the runtime, to the .NET SDK or the CLI, thus I filled it in here.
I cannot reliable reproduce this issue, I hope the exception stack trace already gives a hint what the reason could be.

**Comment by amanbha** [comment] 2019-10-23 16:30
@RicardoNiepel By default Dapr uses port 3500 for Http, when you run multiple DApr

**Comment by amanbha** [comment] 2019-10-23 16:30
Clicked on close by mistake, reopening it.

**Comment by amanbha** [comment] 2019-10-24 12:59
@yaron2 & @youngbupark

@RicardoNiepel for Dapr runtime issue, please open them in Dapr repo.

**Comment by RicardoNiepel** [comment] 2019-10-25 06:23
@amanbha if you think it's a runtime issue, feel free to transfer the issue

**Comment by yaron2** [comment] 2019-10-28 17:50
@RicardoNiepel can you share the code of ingress and actor?

Thanks!

**Comment by RicardoNiepel** [comment] 2019-10-30 07:40
I have enabled log-level debug but only see one new line
`== DAPR == time="2019-10-30T08:24:26+01:00" level=debug msg="error from app: %!!(MISSING)s(<nil>)"`

### Ingress (service) output

```console
dapr run --app-id ingress --app-port 5000 --port 5500 dotnet run --log-level debug
Starting Dapr with id ingress. HTTP Port: 5500. gRPC Port: 60430
You're up and running! Both Dapr and your app logs will appear here.

== DAPR == time="2019-10-30T08:23:55+01:00" level=info msg="starting Dapr Runtime -- version 0.1.0 -- commit 4358565-dirty"
== DAPR == time="2019-10-30T08:23:55+01:00" level=info msg="log level set to: debug"
== DAPR == time="2019-10-30T08:23:55+01:00" level=info msg="standalone mode configured"
== DAPR == time="2019-10-30T08:23:55+01:00" level=info msg="dapr id: ingress"
== DAPR == time="2019-10-30T08:23:55+01:00" level=info msg="loaded component messagebus (pubsub.redis)"
== DAPR == time="2019-10-30T08:23:55+01:00" level=info msg="loaded component statestore (state.redis)"
== DAPR == time="2019-10-30T08:23:55+01:00" level=info msg="application protocol: http. waiting on port 5000"
== APP == info: Microsoft.Hosting.Lifetime[0]
== APP ==       Now listening on: http://localhost:5000
== APP == info: Microsoft.Hosting.Lifetime[0]
== APP ==       Application started. Press Ctrl+C to shut down.
== APP == info: Microsoft.Hosting.Lifetime[0]
== APP ==       Hosting environment: Development
== APP == info: Microsoft.Hosting.Lifetime[0]
== APP ==       Content root path: C:\Sources\pubsub\src\PubSub\PubSub.Ingress
== DAPR == time="2019-10-30T08:23:58+01:00" level=info msg="application discovered on port 5000"
== APP == info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
== APP ==       Request starting HTTP/1.1 GET http://127.0.0.1:5000/dapr/config application/json
== APP == info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
== APP ==       Request finished in 41.6786ms 404
== DAPR == 2019/10/30 08:23:58 redis: connecting to localhost:6379
== DAPR == 2019/10/30 08:23:58 redis: connected to localhost:6379 (localAddr: [::1]:60444, remAddr: [::1]:6379)
== APP == info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
== APP ==       Request starting HTTP/1.1 GET http://127.0.0.1:5000/dapr/subscribe application/json
== APP == info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
== APP ==       Executing endpoint 'dapr/subscribe HTTP: GET'
== APP == info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
== APP ==       Executed endpoint 'dapr/subscribe HTTP: GET'
== APP == info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
== APP ==       Request finished in 32.4687ms 200 application/json
== DAPR == time="2019-10-30T08:23:58+01:00" level=warning msg="redis streams: BUSYGROUP Consumer Group name already exists"
== DAPR == time="2019-10-30T08:23:58+01:00" level=info msg="actor runtime started. actor idle timeout: 1h0m0s. actor scan interval: 30s"
== DAPR == time="2019-10-30T08:23:58+01:00" level=info msg="actors: starting connection attempt to placement service at localhost:6050"
== DAPR == time="2019-10-30T08:23:58+01:00" level=info msg="actors: established connection to placement service at localhost:6050"
== DAPR == time="2019-10-30T08:23:58+01:00" level=info msg="http server is running on port 5500"
== DAPR == time="2019-10-30T08:23:58+01:00" level=info msg="gRPC server is running on port 60430"
== DAPR == time="2019-10-30T08:23:58+01:00" level=info msg="local service entry announced"
== DAPR == time="2019-10-30T08:23:58+01:00" level=info msg="dapr initialized. Status: Running. Init Elapsed 3236.9992ms"
== DAPR == time="2019-10-30T08:23:58+01:00" level=info msg="actors: placement order received: lock"
== DAPR == time="2019-10-30T08:23:58+01:00" level=info msg="actors: placement order received: update"
== DAPR == time="2019-10-30T08:23:58+01:00" level=info msg="actors: placement tables updated"
== DAPR == time="2019-10-30T08:23:58+01:00" level=info msg="actors: placement order received: unlock"
== APP == info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
== APP ==       Request starting HTTP/1.1 POST http://127.0.0.1:5000/route-to-actor application/cloudevents+json 192
== APP == info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
== APP ==       Executing endpoint 'route-to-actor HTTP: POST'
== APP == RouteToActor with 2 and Hallo Max
== APP == info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
== APP ==       Executed endpoint 'route-to-actor HTTP: POST'
== APP == fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
== APP ==       An unhandled exception has occurred while executing the request.
== APP == Dapr.Actors.DaprException: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 169.254.209.113:60194: connectex: No connection could be made because the target machine actively refused it."
== APP ==    at Dapr.Actors.DaprHttpInteractor.SendAsyncHandleUnsuccessfulResponse(Func`1 requestFunc, String relativeUri, String requestId, CancellationToken cancellationToken)  == APP ==    at Dapr.Actors.DaprHttpInteractor.SendAsync(Func`1 requestFunc, String relativeUri, String requestId, CancellationToken cancellationToken)
== APP ==    at Dapr.Actors.DaprHttpInteractor.InvokeActorMethodWithoutRemotingAsync(String actorType, String actorId, String methodName, String jsonPayload, CancellationToken cancellationToken)
== APP ==    at PubSub.Ingress.Startup.<>c__DisplayClass3_0.<<Configure>g__RouteToActor|3>d.MoveNext() in C:\Sources\pubsub\src\PubSub\PubSub.Ingress\Startup.cs:line 108
== APP == --- End of stack trace from previous location where exception was thrown ---
== APP ==    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
== APP ==    at Dapr.CloudEventsMiddleware.ProcessBodyAsync(HttpContext httpContext, String charSet)
== APP ==    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
== DAPR == time="2019-10-30T08:24:23+01:00" level=debug msg="error from app: %!!(MISSING)s(<nil>)"
== APP == info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
== APP ==       Request finished in 4500.0802ms 500 text/plain
```

### Actor output

```console
dapr run --app-id actor --app-port 3000 --port 3500 dotnet run --log-level debug
Starting Dapr with id actor. HTTP Port: 3500. gRPC Port: 60458
You're up and running! Both Dapr and your app logs will appear here.

== DAPR == time="2019-10-30T08:24:12+01:00" level=info msg="starting Dapr Runtime -- version 0.1.0 -- commit 4358565-dirty"
== DAPR == time="2019-10-30T08:24:12+01:00" level=info msg="log level set to: debug"
== DAPR == time="2019-10-30T08:24:12+01:00" level=info msg="standalone mode configured"
== DAPR == time="2019-10-30T08:24:12+01:00" level=info msg="dapr id: actor"
== DAPR == time="2019-10-30T08:24:12+01:00" level=info msg="loaded component messagebus (pubsub.redis)"
== DAPR == time="2019-10-30T08:24:12+01:00" level=info msg="loaded component statestore (state.redis)"
== DAPR == time="2019-10-30T08:24:12+01:00" level=info msg="application protocol: http. waiting on port 3000"
== APP == Hosting environment: Development
== APP == Content root path: C:\Sources\pubsub\src\PubSub\PubSub.ConnectUserActorService
== APP == Now listening on: http://localhost:3000
== APP == Application started. Press Ctrl+C to shut down.
== DAPR == time="2019-10-30T08:24:16+01:00" level=info msg="application discovered on port 3000"
== APP == info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
== APP ==       Request starting HTTP/1.1 GET http://127.0.0.1:3000/dapr/config application/json
== APP == info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
== APP ==       Request finished in 30.376900000000003ms 200
== DAPR == time="2019-10-30T08:24:16+01:00" level=info msg="application configuration loaded"
== DAPR == 2019/10/30 08:24:16 redis: connecting to localhost:6379
== DAPR == 2019/10/30 08:24:16 redis: connected to localhost:6379 (localAddr: [::1]:60476, remAddr: [::1]:6379)
== APP == info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
== APP ==       Request starting HTTP/1.1 GET http://127.0.0.1:3000/dapr/subscribe application/json
== APP == info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
== APP ==       Request finished in 2.2063ms 404
== DAPR == time="2019-10-30T08:24:16+01:00" level=info msg="actor runtime started. actor idle timeout: 1h0m0s. actor scan interval: 30s"
== DAPR == time="2019-10-30T08:24:16+01:00" level=info msg="actors: starting connection attempt to placement service at localhost:6050"
== DAPR == time="2019-10-30T08:24:16+01:00" level=info msg="http server is running on port 3500"
== DAPR == time="2019-10-30T08:24:16+01:00" level=info msg="gRPC server is running on port 60458"
== DAPR == time="2019-10-30T08:24:16+01:00" level=info msg="local service entry announced"
== DAPR == time="2019-10-30T08:24:16+01:00" level=info msg="dapr initialized. Status: Running. Init Elapsed 3762.0019ms"
== DAPR == time="2019-10-30T08:24:16+01:00" level=info msg="actors: established connection to placement service at localhost:6050"
== DAPR == time="2019-10-30T08:24:16+01:00" level=info msg="actors: placement order received: lock"
== DAPR == time="2019-10-30T08:24:16+01:00" level=info msg="actors: placement order received: update"
== DAPR == time="2019-10-30T08:24:16+01:00" level=info msg="actors: placement tables updated"
== DAPR == time="2019-10-30T08:24:16+01:00" level=info msg="actors: placement order received: unlock"
```

### Ingress (service) RouteToActor method
```c#
async Task RouteToActor(HttpContext context)
{
    var command = await JsonSerializer.DeserializeAsync<Command>(context.Request.Body, serializerOptions);

    Console.WriteLine($"RouteToActor with {command.UserId} and {command.Payload}");

    var actorType = IConnectUserActor.ActorType;
    var actorID = new ActorId(command.UserId.ToString());

    var proxy = ActorProxy.Create(actorID, actorType);
    // line 108:
    await proxy.InvokeAsync("SendCommandAsync", command);
}
```

### Actor SendCommandAsync method
```c#
public async Task SendCommandAsync(Command command)
{
    Console.WriteLine($"actor {this.Id} - SendCommandAsync called with {command.Payload}");
}
```

**Comment by RicardoNiepel** [comment] 2019-11-04 15:10
@yaron2 do you need anything else from me?

**Comment by yaron2** [comment] 2019-11-04 15:12
No, we were able to reproduce the issue and already patched a fix for it which isn't updated by the Dapr CLI because of the way to install the Placement Service container. This will be fixed in the next release for 0.2.0.

**Comment by yaron2** [comment] 2019-11-04 15:13
Thanks for reporting!

**Comment by RicardoNiepel** [comment] 2019-11-04 15:29
Awesome, can you pls link the PR/CheckIn of the fix?

I will close this afterwards.

**Comment by yaron2** [comment] 2019-11-07 19:14
https://github.com/dapr/dapr/pull/589

**Closed** 2019-11-08 00:19 UTC
