### ISSUE TITLE
Discord link direct to empty Server

### ISSUE THREAD

**Issue by tshaiman** [dapr/docs#3984] opened 2024-01-28 21:21 UTC
**Describe the issue**
at the buttom of the page there is "Join Discord" invite that points to https://discord.com/channels/778680217417809931
this is empty Discord Server 
![image](https://github.com/dapr/docs/assets/512709/67618cbe-5128-4601-bd76-01182db46c30)

**URL of the docs**
https://docs.dapr.io/getting-started/quickstarts/pubsub-quickstart/

**Expected content**
the link should work

**Comment by marcduiker** [comment] 2024-01-29 09:46
Hi @tshaiman, for me, the link appears to be working and points to the quickstarts channel in the Dapr Discord. The server ID (778680217417809931) also seems to be the correct one. Could you retry? If it is reproducible for you, can you share the browser/OS etc you're using?

**Comment by msfussell** [comment] 2024-02-07 05:42
@tshaiman - Works for me to. Do you have any more information?

**Comment by tshaiman** [comment] 2024-02-07 10:42
that is the information i have
i have created a brand new discord account , logged it 
but when i click on the link i still get this message ![image](https://github.com/dapr/docs/assets/512709/d42b039b-0bec-4d61-96f4-928b7efcd0c1)

**Comment by msfussell** [comment] 2024-10-17 21:05
Could not repo. Closing

**Closed as completed by msfussell** 2024-10-17 21:05 UTC
Labels: P2, content/incorrect-information
