### ISSUE TITLE
Python SDK docs for binding refers to wrong param name

### ISSUE THREAD

**Issue by artursouza** [dapr/docs#2392] opened 2022-04-23 00:32 UTC
**Describe the issue**
Trying out the Python SDK for output binding gives an error in `invoke_binding` if using `name` as param instead of `binding_name`.

**URL of the docs**
https://docs.dapr.io/developing-applications/sdks/python/python-client/#interact-with-output-bindings

**Expected content**
Refer to `binding_name` instead of `name`

**Comment by berndverst** [comment] 2022-04-23 01:27
This is a duplicate. Also it was already fixed in https://github.com/dapr/python-sdk/pull/385

Docs maintainers need to update the git submodule to pull in the latest changes from the Python SDK docs.

**Comment by berndverst** [comment] 2022-04-23 01:28
Duplicate of https://github.com/dapr/docs/issues/1779

**Closed as completed** 2022-06-17 04:58 UTC
Labels: good first issue, content/incorrect-information
