### ISSUE TITLE
Providing code for performance test metrics

### ISSUE THREAD

**Issue by cisionmarkwalls** [dapr/docs#2955] opened 2022-11-14 18:54 UTC
**What content needs to be created or modified?**
For the performance page: https://docs.dapr.io/operations/performance-and-scalability/perf-service-invocation/ there is no link to the code used for this performance test, so it is not reproducible and reduces trust making it harder to get buy-in from DevOps vs known solutions like Istio.

**Describe the solution you'd like**
1. A github link to a reproducible test case
2. A suggestion would be to copy the Istio test case here: https://github.com/istio/tools/tree/release-1.15/perf/load so you can see an apples to apples comparison between the stacks.
3. Perhaps looking at https://istio.io/latest/blog/2019/performance-best-practices/ for performing valuable load testing metrics.

**Where should the new material be placed?**
A link in the documentation would be excellent.

**The associated pull request from dapr/dapr, dapr/components-contrib, or other Dapr code repos**
N/A

**Additional context**
A barrier to getting this implemented in large enterprises is concerns about utilization of resources and latency for all the services that DAPR provides. Giving an open source test case, especially one that mimics a well known tech stack like Istio, would provide strength to the argument that we receive more with DAPR with less resources.

**Comment by berndverst** [comment] 2023-02-23 00:06
See **perf** for all performance tests at https://github.com/dapr/dapr/tree/master/tests

See this article for instructions to run the perf tests https://github.com/dapr/dapr/blob/master/tests/docs/running-perf-tests.md

@tmacam might be able to comment on whether the perf numbers are different since switching from Fortio to K6.

**Comment by berndverst** [comment] 2023-02-23 00:11
@cisionmarkwalls please note that Dapr does not compete with Istio / is not a replacement for Istio. It solves a different use case. For that reason using Istio test cases also does not make sense.

I'll let runtime maintainers @yaron2 and @artursouza chime in more.

**Comment by artursouza** [comment] 2023-02-23 00:26
There are overlaps in some functionalities between Istio and Dapr, mainly service invocation and tracing. Also, Dapr requires app to change endpoint while Istio does not require any code change.

**Comment by yaron2** [comment] 2023-02-23 01:25
In addition to @berndverst pointing to the perf tests source and the instructions for how to reproduce them, I'd mention that we took inspiration from Istio when building the perf tests, all the way from using Fortio as the test tool, to using the same test parameters (QPS, connection size) and more. Another thing to mention is that the current perf stats on our docs are not up-to-date, and today we're seeing ~1.10ms end to end latency as opposed to the 1.4ms in the current version of the docs.

**Comment by hhunter-ms** [comment] 2023-12-21 18:26
closing in favor of related docs issue #3468

**Closed as completed by hhunter-ms** 2023-12-21 18:26 UTC
Labels: content/missing-information
