### ISSUE TITLE
CosmosDb query

### ISSUE THREAD

**Issue by qxecutioner** [dapr/docs#4211] opened 2024-06-17 23:40 UTC
Problem: There should be docs on how querying works on CosmosDB

Description:
Provide all options and documentation on querying CosmosDB

Where to place:
https://docs.dapr.io/reference/components-reference/supported-state-stores/setup-azure-cosmosdb/

**Comment by WhitWaldo** [comment] 2024-06-20 05:47
Dapr isn't an ORM and doesn't provide any sort of rich query system for state management; rather, it's simply providing simple key/value state interactions. While there exists an query API [documented here](https://docs.dapr.io/developing-applications/building-blocks/state-management/howto-state-query-api/) for all supporting state stores containing JSON data, it's in a permanent alpha state and is no longer being iterated on. 

My recommendation is that if you need to create and submit SQL queries against Cosmos or another database, you use their SDK directly in your microservice.

**Comment by hhunter-ms** [comment] 2024-07-30 16:54
@qxecutioner The [Azure Cosmos DB documentation](https://learn.microsoft.com/azure/cosmos-db/introduction) provides several articles for querying Cosmos DB (type 'query' in the 'Filter by title' bar to narrow down). Hopefully that helps. We try not to duplicate official documentation from AWS, Google, Azure, etc. in the Dapr docs.

**Comment by msfussell** [comment] 2024-08-01 21:25
@qxecutioner - Hopefully the replies above answer this.

**Closed as completed by msfussell** 2024-08-01 21:25 UTC
Labels: content/missing-information
