### ISSUE TITLE
Got "REF_NOT_FOUND" error when building this doc site

### ISSUE THREAD

**Issue by seeflood** [dapr/docs#3341] opened 2023-04-18 05:26 UTC
**Describe the bug**

**Steps to reproduce**

1. I followed [the tutorial in the readme](https://github.com/dapr/docs#environment-setup) and run all the commands successfully:
![image](https://user-images.githubusercontent.com/26001097/232678835-5e1f4d3d-548f-41d4-8404-52a284490937.png)

2. But when running `hugo server`, I got errors:
 
```shell
➜  daprdocs git:(v1.10) hugo server

Start building sites … 
hugo v0.111.3+extended darwin/arm64 BuildDate=unknown
ERROR 2023/04/18 13:05:59 [en] REF_NOT_FOUND: Ref "php": "/Users/xxxxxx/projects/dapr-related/docs/daprdocs/content/en/concepts/overview.md:118:9": page not found
WARN 2023/04/18 13:05:59 .Path when the page is backed by a file is deprecated and will be removed in a future release. We plan to use Path for a canonical source path and you probably want to check the source is a file. To get the current behaviour, you can use a construct similar to the one below:

  {{ $path := "" }}
  {{ with .File }}
        {{ $path = .Path }}
  {{ else }}
        {{ $path = .Path }}
  {{ end }}


Re-run Hugo with the flag --panicOnWarning to get a better error message.
ERROR 2023/04/18 13:06:01 [en] REF_NOT_FOUND: Ref "php": "/Users/xxxxxx/projects/dapr-related/docs/daprdocs/content/en/_index.md:198:16": page not found
ERROR 2023/04/18 13:06:01 [en] REF_NOT_FOUND: Ref "php": "/Users/xxxxxx/projects/dapr-related/docs/daprdocs/content/en/developing-applications/sdks/_index.md:38:9": page not found
Error: Error building site: logged 3 error(s)
Built in 3683 ms
```

**Expected behavior**

No error

**Screenshots**

![image](https://user-images.githubusercontent.com/26001097/232679060-59571cfc-ce68-438d-97eb-0e0e6177db9a.png)

**Desktop (please complete the following information):**
 - OS: <img width="140" alt="image" src="https://user-images.githubusercontent.com/26001097/232679163-d0190e06-b357-43c0-9407-790992378ad1.png">

 - Browser 
 - Version 
<img width="564" alt="image" src="https://user-images.githubusercontent.com/26001097/232679246-540d21d2-21ae-4359-8e04-09f15699951e.png">

**Additional context**

**Comment by AaronCrawfis** [comment] 2023-05-26 19:51
@seeflood looks like the issue is with the `php` directory. Could you double check that your submodules were correctly downloaded? The php directory is brought in from the php repo. You can run:

```sh
git submodule update --init --recursive
```

**Comment by msfussell** [comment] 2023-06-01 02:55
@seeflood - I am going to close this issue, based on @AaronCrawfis Comment. Any update?

**Comment by hhunter-ms** [comment] 2023-06-15 16:17
closing - presuming this is resolved

**Closed as completed by hhunter-ms** 2023-06-15 16:17 UTC
Labels: website/functionality
