### ISSUE TITLE
Mismatch of text describing the stage and the diagram representing the stage/example

### ISSUE THREAD

**Issue by coderharee** [dapr/docs#1927] opened 2021-11-10 15:56 UTC
**Text describing the stage/ example states Redis is deployed on namespace-a but the diagram shows its deployed on namespace-b**

**[URL of the docs](https://docs.dapr.io/operations/components/setup-pubsub/pubsub-namespaces/)**

**The text and the diagram should match**

**![image](https://user-images.githubusercontent.com/93363250/141146957-aec1eef5-6c8b-4eeb-bd64-f08db6b7b4cf.png)**

**Comment by msfussell** [comment] 2022-02-24 05:07
This is a duplicate of https://github.com/dapr/docs/issues/2088

**Comment by msfussell** [comment] 2022-03-04 02:18
Resolved

**Closed as completed by msfussell** 2022-03-04 02:18 UTC
Labels: content/incorrect-information
