### ISSUE TITLE
Added Alibaba cloud kafka service support (confluent kafka)

### ISSUE THREAD

**Issue by cshi0** [dapr/docs#1582] opened 2021-06-21 08:44 UTC
## What content needs to be created or modified?
Alibaba Cloud Kafka service Pub/Sub support. (confluent kafka)

Additional context
dapr/components-contrib#968

**Comment by yaron2** [comment] 2021-07-14 16:05
Can you please create the PR for this?

**Comment by yaron2** [comment] 2021-07-14 16:06
We can't put this in `dapr/dapr` until there's docs in place.

**Comment by berndverst** [comment] 2021-08-10 04:22
@cshi0 since this isn't specific to Alibaba cloud, can you please make sure you document this in a vendor neutral way?

For example confluent provides a managed service on AWS, Google Cloud and Azure. https://www.confluent.io/confluent-cloud/

In a way this is similar to to using the MongoDB component to access Azure Cosmos DB. That documentation about Cosmos DB of course does not belong in the Mongo DB component.

**Comment by berndverst** [comment] 2021-08-10 04:29
Is this a duplicate of https://github.com/dapr/docs/pull/1669 ?

**Comment by cshi0** [comment] 2021-08-10 06:37
> Is this a duplicate of #1669 ?

It is the PR for this issue

**Comment by berndverst** [comment] 2022-09-01 21:49
@greenie-msft please close. This will not be completed in contrib.

**Comment by msfussell** [comment] 2023-02-15 23:35
Not implemented

**Closed as completed by msfussell** 2023-02-15 23:35 UTC
Labels: content/missing-information, waiting-on-code-pr
