### ISSUE TITLE
Incorrect app id and pubsub in "How-To: Publish & subscribe 

### ISSUE THREAD

**Issue by dlm** [dapr/docs#2028] opened 2021-12-05 17:19 UTC
**Describe the issue**

**URL of the docs**

**Expected content**

**Screenshots**

**Additional context**

**Comment by msfussell** [comment] 2021-12-28 18:56
This is a duplicate of https://github.com/dapr/docs/issues/2029

**Closed as completed by msfussell** 2021-12-28 18:56 UTC
Labels: duplicate, content/incorrect-information
