### ISSUE TITLE
Actor overview page needs a dedicated "Features" section

### ISSUE THREAD

**Issue by htalvitie** [dapr/docs#1364] opened 2021-04-02 12:37 UTC
**URL of the docs page**
https://docs.dapr.io/developing-applications/building-blocks/actors/actors-overview/#actor-communication

**How is it currently worded?**
The link on "Dapr Actor Features" points to the original overview page.

**How should it be worded?**
The link should probably point to a different page. Not sure which one, though.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by willtsai** [comment] 2021-08-20 22:45
@AaronCrawfis -- should the [content/typo] tag be removed from this since it no longer seems to be a typo fix but rather a new content request?

**Comment by AaronCrawfis** [comment] 2021-08-24 20:38
@willtsai yeah it's definitely not a typo. Actors docs are a little out of date, and we haven't moved the Actors features out of the how-to and into a dedicated landing/overview page. The overall work item is tracked in #804.

I'll close this item as duplicate of the linked item, as it will be addressed as soon as we redo our actor docs.

**Comment by AaronCrawfis** [comment] 2021-08-24 20:39
Thank you @htalvitie for the feedback! We'll make sure to prioritize our actors docs as soon as we can.

**Closed as completed by AaronCrawfis** 2021-08-24 20:38 UTC
Labels: duplicate, area/runtime/actor
