### ISSUE TITLE
Need doc explaining "daprd"

### ISSUE THREAD

**Issue by georgestevens99** [dapr/docs#943] opened 2020-11-20 15:43 UTC
## Expected Behavior

Since daprd is a commonly used command and part of the system I expect that a search for "daprd" will return at least a documentation page that describes what daprd is (what the heck is this thing, anyway?) and how to use the daprd command.

## Actual Behavior

Such a result returns absolutely nothing about daprd.  And one of the returns about VS Code has a broken link.

## Steps to Reproduce the Problem

Search the documents (upper right corner of documents display in V 0.11) for the string daprd.

## Release Note

RELEASE NOTE:

**Comment by AaronCrawfis** [comment] 2020-11-20 17:50
Thanks for the feedback! I'll work with the team on making sure daprd has a place in the docs and is indexed in the search.

I've also rerun the search crawler to catch the VSCode link. We just pushed new changes yesterday that changed the URL.

**Comment by georgestevens99** [comment] 2020-11-20 18:06
Glad to be of help.  I am currently working full time on ramping up using
dapr to become proficient, especially with the .NET SDK using services
written in C#, gRPC and using Visual Studio 2019.  So I will definitely
post issues when I find them.

I am using Docker Desktop as well to run the dapr containers.  It is really
great that everything concerning the dapr related containers automatically
just happens and that all I have to do is just use dapr run to launch my
service, without having to deal with launching the dapr containers as
well.  So far, this is a very streamlined dev process.  Thanks!
George

**Comment by georgestevens99** [comment] 2020-11-20 18:19
PS -- A nice high level overview diagram showing how daprd fits in with
other high level parts of the system would be useful.

Perhaps looking at the system from a user centered point-of-view (developer
centered) showing what command and control interfaces they have at their
disposal and how those interfaces connect with other parts of dapr.

**Comment by AaronCrawfis** [comment] 2021-06-14 21:28
Related to #378

**Comment by AaronCrawfis** [comment] 2021-07-06 21:58
Duplicate of #378

**Closed by AaronCrawfis** 2021-07-06 21:58 UTC
Labels: P1, content/diagram-needed, content/missing-information
