### ISSUE TITLE
Document the shutdown API

### ISSUE THREAD

**Issue by msfussell** [dapr/docs#1363] opened 2021-04-02 01:32 UTC
As a result of this K8s job feature support a new API for shutdown has need introduced that needs to be added to the Dapr API reference docs as a new section. https://docs.dapr.io/reference/api/

http://localhost:3500/v1.0/shutdown

**Comment by AaronCrawfis** [comment] 2021-04-07 23:00
Duplicate of #1386

**Closed as completed by AaronCrawfis** 2021-04-07 23:00 UTC
Labels: duplicate, content/new-feature, content/missing-information
