### ISSUE TITLE
Clarify the output binding request structure for bindings.redis component

### ISSUE THREAD

**Issue by pruthvidhodda** [dapr/docs#508] opened 2020-04-09 00:32 UTC
## Describe the proposal

An output binding request for bindings.redis **should** have "key" in the metadata but that's not documented or at least not clear. It would be better if this point is explicitly mentioned in the docs [here](https://github.com/dapr/docs/blob/master/reference/api/bindings_api.md#payload).

Edit:

The bindings.redis component specifically looks for a key named "key" in the request metadata - see [this](https://github.com/dapr/components-contrib/blob/master/bindings/redis/redis.go#L73). As @msfussell  mentioned below it's better if it's documented in [redis binding spec](https://github.com/dapr/docs/blob/master/reference/specs/bindings/redis.md) just like the way it is done for blob storage binding [here](https://github.com/dapr/docs/blob/master/reference/specs/bindings/blobstorage.md).

**Comment by msfussell** [comment] 2020-04-09 03:48
Agreed. Needs clarification.

**Comment by msfussell** [comment] 2020-04-09 04:48
This should also be documented into the redis binding spec https://github.com/dapr/docs/blob/master/reference/specs/bindings/redis.md

**Comment by AaronCrawfis** [comment] 2020-12-17 00:02
Duplicate of #1001

**Closed by AaronCrawfis** 2020-12-17 00:02 UTC
Labels: duplicate
