### ISSUE TITLE
jQuery CDN not reachable from certain VPNs

### ISSUE THREAD

**Issue by dybxin** [dapr/docs#900] opened 2020-11-10 08:49 UTC
## Ask your question here
https://docs.dapr.io/getting-started/configure-redis/#configure-dapr-components, click button not switch
![Screenshot from 2020-11-10 16-47-29](https://user-images.githubusercontent.com/14888437/98650885-76b9d200-2374-11eb-83e2-2cd644e436b7.png)
additional, click some link find page not found!

**Comment by AaronCrawfis** [comment] 2020-11-17 17:38
Hi @dybxin, thanks for the feedback!

Could you describe your issue a bit more? Is it an issue with the tabbed navigation? Which browser are you using?

**Comment by dybxin** [comment] 2020-11-18 02:40
Hi @AaronCrawfis, I'm sorry. 

No response when clicking on tab navigation in google chrome and firefox.  and the same question in [install dapr cli markdown](https://docs.dapr.io/getting-started/install-dapr-cli/#tabs-1-binaries), click button `Windows` `MacOS` `Binaries`  no change.

**Comment by dybxin** [comment] 2020-11-18 03:22
additional,  click some Link find page not found. 

1. in this page: `https://docs.dapr.io/developing-applications/building-blocks/secrets/secrets-overview/`

2. click link `Setup secret stores`
![Screenshot from 2020-11-18 11-20-01](https://user-images.githubusercontent.com/14888437/99478823-13412d00-2990-11eb-9707-323747c039fd.png)

3. result: page not found

**Comment by AaronCrawfis** [comment] 2020-11-18 17:21
> Hi @AaronCrawfis, I'm sorry.
> 
> No response when clicking on tab navigation in google chrome and firefox. and the same question in [install dapr cli markdown](https://docs.dapr.io/getting-started/install-dapr-cli/#tabs-1-binaries), click button `Windows` `MacOS` `Binaries` no change.

Interesting. Working on reproducing and not hitting the same issue. Are you using the latest Firefox build (83.0)? And are you doing any special javascript blocking?

**Comment by AaronCrawfis** [comment] 2020-11-18 17:21
> 1. https://docs.dapr.io/developing-applications/building-blocks/secrets/secrets-overview/

Good catch, I'll get this updated. Thanks!

**Comment by dybxin** [comment] 2020-11-19 02:23
The version of Firefox I use is 82.0.3. and i not  run any javascript blocking.

**Comment by orizohar** [comment] 2020-12-16 23:53
Can't reproduce, can you try another browser and re-open if issue persists?

**Comment by dybxin** [comment] 2020-12-17 07:40
ok, the problem still exists, Currently, the problem caused i can not get some docs content. if provide some other way help me read markdown? I have tried several browsers, also colleagues have the same problem.

**Comment by AaronCrawfis** [comment] 2020-12-17 19:03
@dybxin reopening.

Interesting, I'll help get to the bottom of this. 

When you open the dev console (right click, inspect element, console) are there any errors being thrown?

Also are you able to join our discord server (https://aka.ms/dapr-discord) and message me there? I can hop on a chat to diagnose in real time.

**Comment by dybxin** [comment] 2020-12-18 02:03
@AaronCrawfis thanks a lot.
following is errors the console output.
![Screenshot from 2020-12-18 10-00-47](https://user-images.githubusercontent.com/14888437/102565313-2e7e9400-4118-11eb-849c-c7bf01d0405f.png)

**Comment by AaronCrawfis** [comment] 2020-12-18 02:06
@dybxin what happens when you visit http://code.jquery.com/jquery-3.5.1.min.js directly on your browser?

**Comment by dybxin** [comment] 2020-12-18 02:12
@AaronCrawfis  i visit http://code.jquery.com/jquery-3.5.1.min.js directly, the result is refused to connect.
![Screenshot from 2020-12-18 10-11-57](https://user-images.githubusercontent.com/14888437/102565979-7c47cc00-4119-11eb-82c0-c1c1d4cbdbae.png)

**Comment by AaronCrawfis** [comment] 2020-12-18 02:21
@dybxin

One more test: try a ping and trace route:

```
ping code.jquery.com
```

```
tracert code.jquery.com
```

**Comment by dybxin** [comment] 2020-12-18 02:32
@AaronCrawfis 
the `ping code jquery.com` output:
```json
PING cds.s5x3j6q5.hwcdn.net (209.197.3.24) 56(84) bytes of data.
64 bytes from vip0x018.map2.ssl.hwcdn.net (209.197.3.24): icmp_seq=1 ttl=47 time=271 ms
64 bytes from vip0x018.map2.ssl.hwcdn.net (209.197.3.24): icmp_seq=2 ttl=47 time=293 ms
64 bytes from vip0x018.map2.ssl.hwcdn.net (209.197.3.24): icmp_seq=3 ttl=47 time=316 ms
64 bytes from vip0x018.map2.ssl.hwcdn.net (209.197.3.24): icmp_seq=4 ttl=47 time=341 ms
64 bytes from vip0x018.map2.ssl.hwcdn.net (209.197.3.24): icmp_seq=5 ttl=47 time=263 ms
64 bytes from vip0x018.map2.ssl.hwcdn.net (209.197.3.24): icmp_seq=6 ttl=47 time=286 ms
64 bytes from vip0x018.map2.ssl.hwcdn.net (209.197.3.24): icmp_seq=7 ttl=47 time=304 ms
64 bytes from vip0x018.map2.ssl.hwcdn.net (209.197.3.24): icmp_seq=8 ttl=47 time=327 ms
64 bytes from vip0x018.map2.ssl.hwcdn.net (209.197.3.24): icmp_seq=9 ttl=47 time=350 ms
64 bytes from vip0x018.map2.ssl.hwcdn.net (209.197.3.24): icmp_seq=10 ttl=47 time=270 ms
64 bytes from vip0x018.map2.ssl.hwcdn.net (209.197.3.24): icmp_seq=11 ttl=47 time=242 ms
64 bytes from vip0x018.map2.ssl.hwcdn.net (209.197.3.24): icmp_seq=12 ttl=47 time=316 ms
64 bytes from vip0x018.map2.ssl.hwcdn.net (209.197.3.24): icmp_seq=13 ttl=47 time=339 ms
64 bytes from vip0x018.map2.ssl.hwcdn.net (209.197.3.24): icmp_seq=14 ttl=47 time=251 ms
64 bytes from vip0x018.map2.ssl.hwcdn.net (209.197.3.24): icmp_seq=15 ttl=47 time=283 ms
64 bytes from vip0x018.map2.ssl.hwcdn.net (209.197.3.24): icmp_seq=16 ttl=47 time=306 ms
64 bytes from vip0x018.map2.ssl.hwcdn.net (209.197.3.24): icmp_seq=17 ttl=47 time=328 ms
64 bytes from vip0x018.map2.ssl.hwcdn.net (209.197.3.24): icmp_seq=18 ttl=47 time=349 ms
64 bytes from vip0x018.map2.ssl.hwcdn.net (209.197.3.24): icmp_seq=19 ttl=47 time=271 ms
```
the `tracert code.jquery.com` output:
code.jquery.com: Network is unreachable

**Comment by AaronCrawfis** [comment] 2020-12-18 03:11
Turns to be an issue with the VPN of the user. As a workaround one can clone repo, find and replace:
`http://code.jquery.com/jquery-3.5.1.min.js`
to
`https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js`

and then serve docs locally

**Comment by nesherhh** [comment] 2021-09-20 14:11
I can confirm the issue. I'm from germany. Not using any VPN. 
Visiting direct - http://code.jquery.com/jquery-3.5.1.min.js gives me 
![image](https://user-images.githubusercontent.com/15830920/134017119-068b93d9-d45f-4d8b-b61f-93a1550c4a22.png)
after hitting F5 about 10 times I get the content of the file. But after some idle time hitting F5 gives me again ERR_CONNECTION_RESET

**Comment by sanderobdeijn** [comment] 2022-01-01 16:47
I have the same issue without a vpn in the Netherlands.
I have no problem loading https://code.jquery.com/jquery-3.5.1.min.js directly.
But I do get an ERR_CONNECTION_CLOSED on the URL in the dapr doc page.

A workaround I found is open the dev console and pressing F5 until you get a load without errors and then the navigation works for me.

It seems to be a flaky bug.

**Comment by tonyqus** [comment] 2022-01-01 23:11
Germany and China are same. They both have big LAN instead of real Internet. I don't think this issue can be reproduced by someone who have real Internet. 

@dybxin I've confirmed that this website is accessible in China https://www.boce.com/http/code.jquery.com. 

![image](https://user-images.githubusercontent.com/772561/147862202-fc227eca-99ca-40a1-a8ff-b26e3d000791.png)


And I can download [this file]( http://code.jquery.com/jquery-3.5.1.min.js) without VPN on my browser. Please double check with your telecommunication provider.  I'm using China-telecom network in Shanghai.

Another possible case is that GFW is randomly throwing network package for this website. If that's the case, there is nothing we can do.

**Comment by hhunter-ms** [comment] 2023-07-13 16:15
Seems to have been resolved - closing. Feel free to reopen if necessary.

**Closed by hhunter-ms** 2023-07-13 16:15 UTC
Labels: P2, website/rendering
